baseURL = 'https://kcmagicpixel.com/'
enableGitInfo = true
enableRobotsTXT = true
languageCode = 'en-us'
summaryLength = 30
title = 'Magic Pixel'
ignoreLogs = ['warning-goldmark-raw-html']
capitalizeListTitles = false
timeZone = "America/Chicago"
buildFuture = true

[params]
altnames = ['KC Magic Pixel', 'Magic Pixel KC', 'Magic Pixel FGC', 'Magic Pixel Fighting Games']
subtitle = 'Kansas City Fighting Game Community Events'

[permalinks]
events = '/:section/:year/:month/:slug'

[frontmatter]
date = ['date', 'start_date']

[taxonomies]
event-series = 'series'
games = 'games'